# Generated by Django 2.0.8 on 2019-06-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_elite_nor_pre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('AC sleeper', 'AC sleeper'), ('Non-AC sleeper', 'Non-AC sleeper'), ('AC Multi Axle Semi sleeper', 'AC Multi Axle Semi sleeper'), ('AC seater', 'AC seater'), ('Super Luxery', 'Super Luxery'), ('Deluxe', 'Deluxe')], max_length=30)),
                ('bus_no', models.CharField(max_length=30)),
            ],
        ),
    ]
