# Generated by Django 2.0.8 on 2019-06-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elite',
            name='destination',
            field=models.CharField(choices=[('HYDERABAD', 'HYDERABAD'), ('BANGOLORE', 'BANGOLORE'), ('VISAKHAPATNAM', 'VISAKHAPATNAM'), ('VIJAYAWADA', 'VIJAYAWADA'), ('GUNTUR', 'GUNTUR'), ('TIRUPATHI', 'TIRUPATHI')], max_length=30),
        ),
        migrations.AlterField(
            model_name='elite',
            name='source',
            field=models.CharField(choices=[('HYDERABAD', 'HYDERABAD'), ('BANGOLORE', 'BANGOLORE'), ('VISAKHAPATNAM', 'VISAKHAPATNAM'), ('VIJAYAWADA', 'VIJAYAWADA'), ('GUNTUR', 'GUNTUR'), ('TIRUPATHI', 'TIRUPATHI')], max_length=30),
        ),
        migrations.AlterField(
            model_name='nor',
            name='destination',
            field=models.CharField(choices=[('HYDERABAD', 'HYDERABAD'), ('BANGOLORE', 'BANGOLORE'), ('VISAKHAPATNAM', 'VISAKHAPATNAM'), ('VIJAYAWADA', 'VIJAYAWADA'), ('GUNTUR', 'GUNTUR'), ('TIRUPATHI', 'TIRUPATHI')], max_length=30),
        ),
        migrations.AlterField(
            model_name='nor',
            name='source',
            field=models.CharField(choices=[('HYDERABAD', 'HYDERABAD'), ('BANGOLORE', 'BANGOLORE'), ('VISAKHAPATNAM', 'VISAKHAPATNAM'), ('VIJAYAWADA', 'VIJAYAWADA'), ('GUNTUR', 'GUNTUR'), ('TIRUPATHI', 'TIRUPATHI')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pre',
            name='destination',
            field=models.CharField(choices=[('HYDERABAD', 'HYDERABAD'), ('BANGOLORE', 'BANGOLORE'), ('VISAKHAPATNAM', 'VISAKHAPATNAM'), ('VIJAYAWADA', 'VIJAYAWADA'), ('GUNTUR', 'GUNTUR'), ('TIRUPATHI', 'TIRUPATHI')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pre',
            name='source',
            field=models.CharField(choices=[('HYDERABAD', 'HYDERABAD'), ('BANGOLORE', 'BANGOLORE'), ('VISAKHAPATNAM', 'VISAKHAPATNAM'), ('VIJAYAWADA', 'VIJAYAWADA'), ('GUNTUR', 'GUNTUR'), ('TIRUPATHI', 'TIRUPATHI')], max_length=30),
        ),
    ]
