# Generated by Django 2.0.8 on 2019-06-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190615_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='elite',
            name='bus_no',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='nor',
            name='bus_no',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='pre',
            name='bus_no',
            field=models.CharField(default='', max_length=30),
        ),
    ]
