# Generated by Django 2.0.8 on 2019-06-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190615_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pid',
            field=models.IntegerField(default='0903'),
        ),
    ]
