# Generated by Django 2.0.8 on 2019-06-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20190615_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elite',
            name='bookd',
        ),
        migrations.RemoveField(
            model_name='nor',
            name='bookd',
        ),
        migrations.RemoveField(
            model_name='pre',
            name='bookd',
        ),
        migrations.AlterField(
            model_name='user',
            name='pid',
            field=models.IntegerField(default='4262'),
        ),
    ]
