# Generated by Django 2.0.8 on 2019-06-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20190619_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='elite',
            name='bus',
            field=models.ForeignKey(default='', on_delete='', to='myapp.Bus'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pid',
            field=models.IntegerField(default='8234'),
        ),
    ]
