# Generated by Django 2.0.8 on 2019-06-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20190619_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elite',
            name='bus',
        ),
        migrations.AlterField(
            model_name='elite',
            name='bus_no',
            field=models.ForeignKey(default='', on_delete='', to='myapp.Bus'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pid',
            field=models.IntegerField(default='7548'),
        ),
    ]
