# Generated by Django 2.0.8 on 2019-06-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20190619_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elite',
            name='lower_births',
        ),
        migrations.RemoveField(
            model_name='elite',
            name='upper_births',
        ),
        migrations.AlterField(
            model_name='user',
            name='pid',
            field=models.IntegerField(default='1107'),
        ),
    ]
