# Generated by Django 2.0.8 on 2019-06-19 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20190619_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='elite',
            name='Pname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
        migrations.AddField(
            model_name='nor',
            name='Pname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
        migrations.AddField(
            model_name='pre',
            name='Pname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
        migrations.AlterField(
            model_name='nor',
            name='bus_no',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.Bus'),
        ),
        migrations.AlterField(
            model_name='pre',
            name='bus_no',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.Bus'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pid',
            field=models.IntegerField(default='9226'),
        ),
    ]
