# Generated by Django 2.0.8 on 2019-06-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_auto_20190619_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elite',
            old_name='Pname',
            new_name='Psname',
        ),
        migrations.RenameField(
            model_name='nor',
            old_name='Pname',
            new_name='Psname',
        ),
        migrations.RenameField(
            model_name='pre',
            old_name='Pname',
            new_name='Psname',
        ),
        migrations.AlterField(
            model_name='user',
            name='pid',
            field=models.IntegerField(default='5222'),
        ),
    ]
